apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: if-sample
  namespace: argocd
spec:
  destination:
    namespace: ifsample
    server: https://kubernetes.default.svc
  source:
    path: manifests
    repoURL: https://github.com/hideto0710/argocd-helm-if-sample.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: false
